name: Deploy react
on:
  push:
    branches: [master]

jobs:
  build_test_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 16.13.2

      - name: Install Dependencies
        run: |
          yarn install

      - name: Build
        run: |
          git config --global user.email "u483198f@gmail.com" 
          git config --global user.name "Ryo Ueda"
          yarn deploy
        env:
          CI: false
